<?php
/**
 * This file is part of AwesomeCheckout.
 *
 * AwesomeCheckout is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AwesomeCheckout is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with AwesomeCheckout.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php $_code = $this->getMethodCode() ?>
<script type="text/javascript">
	//<![CDATA[
	Validation.creditCartTypes.set('JCB', [new RegExp('^(35[0-9]{14}|(2131|1800)[0-9]{11})$'), new RegExp('^([0-9]{3})?$'), true]);
	Validation.creditCartTypes.set('LASER', [new RegExp('^((6304|6706|6771|6709)[0-9]{12}([0-9]{3}))$'), new RegExp('^([0-9]{3})?$'), false]);
	Validation.creditCartTypes.set('UATP', [false, new RegExp('^[0-9]{3}([0-9]{1})?$'), false]);
	Validation.creditCartTypes.set('MCI', [false, new RegExp('^[0-9]{3}([0-9]{1})?$'), false]);
	//]]>
</script>
<ul class="form-list payment-form" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<div class="ac-cc">
		<?php if ( Mage::app()->getStore()->isCurrentlySecure() ) { ?>
			<div class="ssl-img"></div>
		<?php } ?>
		<li class="form">
			<label for="<?php echo $_code ?>_cc_number" class="required cc_number"><?php echo $this->__( 'Credit Card Number' ) ?><em>*</em></label>
			<div class="input-box">
				<input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__( 'Credit Card Number' ) ?>" class="input-text validate-cc-number validate-cc-type" value="" placeholder="4111 1111 1111 1111" pattern="\d*" novalidate />
				<span class="ieplaceholder">4111 1111 1111 1111</span>
			</div>
		</li>
		<li class="cc-item2">
			<?php $_ccType = $this->getInfoData( 'cc_type' ) ?>
			<ul id="<?php echo $_code ?>_cards" class="cards">
				<li class="VI off"><?php echo $this->__('Visa'); ?></li>
				<li class="MC off"><?php echo $this->__('MasterCard'); ?></li>
				<li class="AE off"><?php echo $this->__('American Express'); ?></li>
				<li class="DI off"><?php echo $this->__('Discover'); ?></li>
			</ul>
			<input type="hidden" id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" value="<?php echo $_ccType ?>" class="cc_type" />
		</li>
		<li class="form exp-input">
			<label for="<?php echo $_code ?>_expiration" class="required"><?php echo $this->__( 'Expiration Date' ) ?><em>*</em></label>
			<div class="input-box">
				<div class="v-fix">
					<select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required">
						<?php $_ccExpMonth = $this->getInfoData( 'cc_exp_month' ) ?>
						<?php foreach ( $this->getCcMonths() as $k => $v ): ?>
							<option value="<?php echo $k ? $k : '' ?>"<?php if ( $k == $_ccExpMonth ): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
						<?php endforeach ?>
					</select>
					<span>/</span>
				</div>
				<div class="v-fix">
					<?php $_ccExpYear = $this->getInfoData( 'cc_exp_year' ) ?>
					<select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
						<?php foreach ( $this->getCcYears() as $k => $v ): ?>
							<option value="<?php echo $k ? $k : '' ?>"<?php if ( $k == $_ccExpYear ): ?> selected="selected"<?php endif ?>><?php echo $k ? substr( $v, 2 ) : $v; ?></option>
						<?php endforeach ?>
					</select>
				</div>
			</div>
		</li>
		<?php echo $this->getChildHtml() ?>
		<?php if ( $this->hasVerification() ): ?>
			<li class="form cvv-input">
				<label for="<?php echo $_code ?>_cc_cid" class="required"><?php echo $this->__( 'Credit Card Security Code' ) ?><em>*</em></label>
				<div class="input-box">
					<div class="v-fix">
						<input type="text" title="<?php echo $this->__( 'Credit Card Security Code' ) ?>" class="input-text cvv required validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" placeholder="324" pattern="\d*" novalidate />
						<span class="ieplaceholder">324</span>
					</div>
					<span href="#" class="cvv-what-is-this"><?php echo $this->__( 'What is this?' ) ?></span>
				</div>
			</li>
		<?php endif; ?>
		<?php if ( $this->hasSsCardType() ): ?>
			<li id="<?php echo $_code ?>_cc_type_ss_div">
				<ul class="inner-form">
					<li class="form-alt"><label for="<?php echo $_code ?>_cc_issue" class="required"><em>*</em><?php echo $this->__( 'Switch/Solo/Maestro Only' ) ?></label></li>
					<li>
						<label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__( 'Issue Number' ) ?>:</label>
						<span class="input-box">
							<input type="text" title="<?php echo $this->__( 'Issue Number' ) ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
						</span>
					</li>

					<li>
						<label for="<?php echo $_code ?>_start_month"><?php echo $this->__( 'Start Date' ) ?>:</label>
						<div class="input-box">
							<div class="v-fix">
								<select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
									<?php foreach ( $this->getCcMonths() as $k => $v ): ?>
										<option value="<?php echo $k ? $k : '' ?>"<?php if ( $k == $this->getInfoData( 'cc_ss_start_month' ) ): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
									<?php endforeach ?>
								</select>
							</div>
							<div class="v-fix">
								<select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
									<?php foreach ( $this->getSsStartYears() as $k => $v ): ?>
										<option value="<?php echo $k ? $k : '' ?>"<?php if ( $k == $this->getInfoData( 'cc_ss_start_year' ) ): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
					</li>
					<li class="adv-container">&nbsp;</li>
				</ul>
				<script type="text/javascript">
					//<![CDATA[
					var SSChecked<?php echo $_code ?> = function() {
						var elm = $('<?php echo $_code ?>_cc_type');
						if (elm.value=='SO' || elm.value=='SM') {
							$('<?php echo $_code ?>_cc_type_ss_div').show();
						} else {
							$('<?php echo $_code ?>_cc_type_ss_div').hide();
						}
					};

					Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
					SSChecked<?php echo $_code ?>();
					//]]>
				</script>
			</li>
		<?php endif; ?>
	</div>
</ul>
