<?php
/**
 * This file is part of AwesomeCheckout.
 *
 * AwesomeCheckout is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AwesomeCheckout is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with AwesomeCheckout.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php echo $this->getChildHtml( 'items_before' ); ?>
<header>
		<span>3</span><h2><?php echo $this->__( 'Order Summary' ) ?></h2>
</header>
<div class="top-placeyourorder-btn">
	<?php echo $this->getChildHtml( 'button' ) ?>
</div>
<div id="checkout-review-table-wrapper">
	<table class="data-table" id="checkout-review-table">
		<?php
		if ( $this->helper( 'tax' )->displayCartBothPrices() ): $colspan = $rowspan = 2;
		else: $colspan = $rowspan = 1;
		endif;
		?>
		<col />
		<col width="1" />
		<col width="1" />
		<col width="1" />
		<?php if ( $this->helper( 'tax' )->displayCartBothPrices() ): ?>
			<col width="1" />
			<col width="1" />
		<?php endif; ?>
		<thead>
			<tr>
				<th rowspan="<?php echo $rowspan ?>"><?php echo $this->__( 'Product Name' ) ?></th>
				<th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__( 'Price' ) ?></th>
				<th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__( 'Qty' ) ?></th>
				<th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__( 'Subtotal' ) ?></th>
			</tr>
			<?php if ( $this->helper( 'tax' )->displayCartBothPrices() ): ?>
				<tr>
					<th class="a-right"><?php echo $this->helper( 'tax' )->getIncExcTaxLabel( false ) ?></th>
					<th><?php echo $this->helper( 'tax' )->getIncExcTaxLabel( true ) ?></th>
					<th class="a-right"><?php echo $this->helper( 'tax' )->getIncExcTaxLabel( false ) ?></th>
					<th><?php echo $this->helper( 'tax' )->getIncExcTaxLabel( true ) ?></th>
				</tr>
			<?php endif; ?>
		</thead>
		<?php echo $this->getChildHtml( 'totals' ); ?>
		<tbody>
			<?php foreach ( $this->getItems() as $_item ): ?>
				<?php echo $this->getItemHtml( $_item ) ?>
			<?php endforeach ?>
		</tbody>
	</table>
	<?php echo $this->getChildHtml( 'items_after' ); ?>
	<?php echo $this->getChildHtml( 'coupon' ) ?>
	<div id="onepage-checkout-shipping-method-additional-load">
		<?php echo $this->getChildHtml( 'additional' ) ?>
	</div>
	<?php
	// don't want to do anything if newsletter functionality is disabled in admin
	if ( Mage::getStoreConfigFlag( 'awesomecheckout/newsletter/enable' ) && Mage::getStoreConfigFlag( 'awesomecheckout/newsletter/ask_the_user' ) ) {
		//getting customer email & showing the checkbox only if the user is not already subscribed
		$email = Mage::getSingleton('checkout/session')->getQuote()->getCustomerEmail();
		$status = Mage::getModel( 'newsletter/subscriber' )->loadByEmail( $email )->getStatus();
		if ( $status != Mage_Newsletter_Model_Subscriber::STATUS_SUBSCRIBED ) {
			echo $this->getChildHtml( 'newsletter' );
		}
	}
	?>
	<div class="agreements">
		<?php echo $this->getChildHtml( 'agreements' ) ?>
	</div>
</div>
<footer>
	<div id="checkout-review-submit" class="clearfix">
		<div id="review-place-order">
			<div id="review-buttons-container">
				<?php echo $this->getChildHtml( 'button' ) ?>
				<div>
					<span class="please-wait" id="review-please-wait" style="display:none;">
						<img src="<?php echo $this->getSkinUrl( 'images/anattadesign/awesomecheckout/opc-ajax-loader.gif' ) ?>" alt="<?php echo $this->__( 'Submitting order information...' ) ?>" title="<?php echo $this->__( 'Submitting order information...' ) ?>" class="v-middle" /> <?php echo $this->__( 'Submitting order information...' ) ?>
					</span>
				</div>
			</div>
		</div>
	</div>
</footer>

<?php $saveurl = $this->getUrl( 'checkout/onepage/saveOrder' ); ?>
<?php if ( Mage::helper( 'anattadesign_awesomecheckout/edition' )->isExtensionEnabled( 'Ebizmarts_SagePaySuite' ) && ( $this->helper( 'sagepaysuite' )->isMagentoEE113OrUp() || $this->helper( 'sagepaysuite' )->isMagentoCE1800rUp() ) ) { ?>
	<?php $saveurl = $this->getUrl( 'checkout/onepage/saveOrder', array( 'form_key' => Mage::getSingleton( 'core/session' )->getFormKey() ) ); ?>
<?php } ?>

<script type="text/javascript">
	//<![CDATA[
	review = new Review({saveUrl: '<?php echo $saveurl; ?>', successUrl: '<?php echo $this->getUrl( 'checkout/onepage/success' ) ?>', agreementsForm: '#checkout-agreements', giftMessageForm:'#co-gift-form', newsletterForm:'#newsletter-form'});
	//]]>
</script>

<?php if ( Mage::helper( 'anattadesign_awesomecheckout/edition' )->isExtensionEnabled( 'Ebizmarts_SagePaySuite' ) ) { ?>
	<script type="text/javascript">
		//<![CDATA[
		SageServer = new EbizmartsSagePaySuite.Checkout({
			'checkout':  checkout,
			'review':    review,
			'payment':   payment,
			'billing':   billing,
			'accordion': accordion
		});
		//]]>
	</script>
<?php } ?>

<script type="text/javascript">
	//<![CDATA[
	decorateTable('checkout-review-table');
	truncateOptions();
	//]]>
</script>