<?php
/**
 * This file is part of AwesomeCheckout.
 *
 * AwesomeCheckout is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AwesomeCheckout is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with AwesomeCheckout.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<div id="promo-code">
	<span id="coupon-cancel-link" style="display: none;"><a href="javascript:void(0)" onClick="checkout.cancelCoupon()"><?php echo $this->__( 'Click here to cancel Promo Code' ) ?></a></span>
	<span class="please-wait" id="coupon-cancel-please-wait" style="display:none;">
		<img src="<?php echo $this->getSkinUrl( 'images/anattadesign/awesomecheckout/opc-ajax-loader.gif' ) ?>" alt="<?php echo $this->__( 'Canceling Coupon...' ) ?>" title="<?php echo $this->__( 'Canceling Coupon...' ) ?>" class="v-middle" /> <?php echo $this->__( 'Canceling Coupon...' ) ?>
	</span>
	<a id="coupon-apply-link" style="display: none;" href="javascript:void(0)" onClick="jQuery('#discount-coupon-form-wrapper').slideToggle(400)"><?php echo $this->__( 'Click here if you have a Promo Code' ) ?></a>
</div>

<div id="discount-coupon-form-wrapper"<?php if ( !strlen( $this->getCouponCode() ) ): ?> style="display:none;"<?php endif; ?>>
	<form id="discount-coupon-form" action="<?php echo $this->getUrl( 'checkout/cart/couponPost', Mage::app()->getStore()->isCurrentlySecure() ? array('_forced_secure' => true) : array('_forced_secure' => false) ) ?>" method="post">
		<div class="discount">
			<h2><?php echo $this->__( 'Promo Code' ) ?></h2>
			<div class="discount-form">
				<input type="hidden" name="remove" id="remove-coupone" value="0" />
				<input type="hidden" id="coupon-reload-step-name" name="reload_step_name" value="review" />
				<input type="hidden" id="coupon-reload-step-block" name="reload_step_block" value="checkout_onepage_review" />
				<div class="input-box clearfix">
					<input class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape( $this->getCouponCode() ) ?>" />
					<button id="coupon_apply_button" type="button" title="<?php echo $this->__( 'Apply Coupon' ) ?>" class="button" onclick="checkout.applyCoupon()" value="<?php echo $this->__( 'Apply Coupon' ) ?>"><?php echo $this->__( 'Apply' ) ?></button>
					<span class="please-wait" id="coupon-apply-please-wait" style="display:none;">
						<img src="<?php echo $this->getSkinUrl( 'images/anattadesign/awesomecheckout/opc-ajax-loader.gif', Mage::app()->getStore()->isCurrentlySecure() ? array('_forced_secure' => true) : array('_forced_secure' => false)  ) ?>" alt="<?php echo $this->__( 'Applying Coupon...' ) ?>" title="<?php echo $this->__( 'Applying Coupon...' ) ?>" class="v-middle" /> <?php echo $this->__( 'Applying Coupon...' ) ?>
					</span>
				</div>
			</div>
		</div>
	</form>
</div>

<script>
	<?php if ( strlen( Mage::getSingleton( 'checkout/session' )->getQuote()->getCouponCode() ) ): ?>
		jQuery('#coupon-cancel-link').show();
	<?php else: ?>
		jQuery('#coupon-apply-link').show();
	<?php endif; ?>

	/* Intercept the Enter keypress to submit the coupon instead of the main checkout step */
	jQuery("#discount-coupon-form-wrapper").keypress(function(e) {
		if (e.which == 13) {
			if (jQuery(this).find("input").is(":focus")) {
				e.preventDefault();
				checkout.applyCoupon();
			}
		}
	});
</script>