<?php
/**
 * This file is part of AwesomeCheckout.
 *
 * AwesomeCheckout is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AwesomeCheckout is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with AwesomeCheckout.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php
$_form = $this;
$_code = $_form->getMethodCode();
$_method = $_form->getMethod();
$_model = Mage::getModel( 'braintree/paymentmethod' );
if(!$_model){
	$_model = Mage::getModel( 'braintree_payments/paymentmethod' );
}
$_loggedIn = Mage::app()->isInstalled() && Mage::getSingleton( 'customer/session' )->isLoggedIn();
$_storedCards = $_model->currentCustomerStoredCards();
$_useVault = $_loggedIn && $_model->useVault() && count( $_storedCards );
?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<div class="ac-cc">
		<?php if ( Mage::app()->getStore()->isCurrentlySecure() ) { ?>
			<div class="ssl-img"></div>
		<?php } ?>
		<?php if ( $_useVault ): ?>
			<li id="<?php echo $_code ?>_token_selector" class="form">
				<label for="<?php echo $_code ?>_cc_token"><?php echo $this->__( 'Saved Credit Cards' ) ?></label>

				<div class="input-box">
					<select id="<?php echo $_code ?>_cc_token" name="payment[cc_token]">
						<?php foreach ( $_storedCards as $creditCard ): ?>
							<option value="<?php echo $creditCard->token ?>">
								<?php echo $creditCard->maskedNumber ?>
							</option>
						<?php endforeach; ?>
						<option value=''><?php echo $this->__( 'Add new card' ) ?></option>
					</select>
				</div>
			</li>
		<?php endif; ?>

		<li class="hide_if_token_selected form">
			<label for="<?php echo $_code ?>_cc_number" class="required"><?php echo $this->__( 'Credit Card Number' ) ?><em>*</em></label>
			<div class="input-box">
				<input type="text" id="<?php echo $_code ?>_cc_number" data-encrypted-name="payment[cc_number]" title="<?php echo $this->__( 'Credit Card Number' ) ?>" class="input-text required-entry validate-cc-number validate-digits" value="" placeholder="4111 1111 1111 1111" pattern="\d*" novalidate />
				<span class="ieplaceholder">4111 1111 1111 1111</span>
			</div>
		</li>
		<li class="hide_if_token_selected cc-item2">
			<?php $_ccType = $this->getInfoData( 'cc_type' ) ?>
			<ul id="<?php echo $_code ?>_cards" class="cards">
				<li class="VI off"><?php echo $this->__('Visa'); ?></li>
				<li class="MC off"><?php echo $this->__('MasterCard'); ?></li>
				<li class="AE off"><?php echo $this->__('American Express'); ?></li>
				<li class="DI off"><?php echo $this->__('Discover'); ?></li>
			</ul>
			<input type="hidden" id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" value="<?php echo $_ccType ?>" class="cc_type" />
		</li>
		<li class="hide_if_token_selected form exp-input">
			<label for="<?php echo $_code ?>_expiration" class="required"><?php echo $this->__( 'Expiration Date' ) ?><em>*</em></label>
			<div class="input-box">
				<div class="v-fix">
					<select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
						<?php $_ccExpMonth = $this->getInfoData( 'cc_exp_month' ) ?>
						<?php foreach ( $this->getCcMonths() as $k => $v ): ?>
							<option value="<?php echo $k ? $k : '' ?>"<?php if ( $k == $_ccExpMonth ): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
						<?php endforeach ?>
					</select>
					<span>/</span>
				</div>
				<div class="v-fix">
					<?php $_ccExpYear = $this->getInfoData( 'cc_exp_year' ) ?>
					<select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
						<?php foreach ( $this->getCcYears() as $k => $v ): ?>
							<option value="<?php echo $k ? $k : '' ?>"<?php if ( $k == $_ccExpYear ): ?> selected="selected"<?php endif ?>><?php echo $k ? substr( $v, 2 ) : $v; ?></option>
						<?php endforeach ?>
					</select>
				</div>
			</div>
		</li>
		<?php echo $this->getChildHtml() ?>
		<?php if ( $this->hasVerification() ): ?>
			<li class="hide_if_token_selected form cvv-input">
				<label for="<?php echo $_code ?>_cc_cid" class="required"><?php echo $this->__( 'Credit Card Security Code' ) ?><em>*</em></label>
				<div class="input-box">
					<div class="v-fix">
						<input type="text" title="<?php echo $this->__( 'Credit Card Security Code' ) ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" data-encrypted-name="payment[cc_cid]" value="" placeholder="324" pattern="\d*" novalidate />
						<span class="ieplaceholder">324</span>
					</div>
					<a href="#" class="cvv-what-is-this"><?php echo $this->__( 'What is this?' ) ?></a>
				</div>
			</li>
		<?php endif; ?>
		<?php if ( $this->hasSsCardType() ): ?>
			<li id="<?php echo $_code ?>_cc_type_ss_div" class="hide_if_token_selected">
				<ul class="inner-form">
					<li class="form-alt"><label for="<?php echo $_code ?>_cc_issue" class="required"><em>*</em><?php echo $this->__( 'Switch/Solo/Maestro Only' ) ?></label></li>
					<li>
						<label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__( 'Issue Number' ) ?>:</label>
						<span class="input-box">
							<input type="text" title="<?php echo $this->__( 'Issue Number' ) ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value=""/>
						</span>
					</li>

					<li>
						<label for="<?php echo $_code ?>_start_month"><?php echo $this->__( 'Start Date' ) ?>:</label>

						<div class="input-box">
							<div class="v-fix">
								<select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
									<?php foreach ( $this->getCcMonths() as $k => $v ): ?>
										<option value="<?php echo $k ? $k : '' ?>"<?php if ( $k == $this->getInfoData( 'cc_ss_start_month' ) ): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
									<?php endforeach ?>
								</select>
							</div>
							<div class="v-fix">
								<select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
									<?php foreach ( $this->getSsStartYears() as $k => $v ): ?>
										<option value="<?php echo $k ? $k : '' ?>"<?php if ( $k == $this->getInfoData( 'cc_ss_start_year' ) ): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
					</li>
					<li class="adv-container">&nbsp;</li>
				</ul>
			</li>
		<?php endif; ?>

		<?php if ( $_loggedIn && $_model->useVault() ): ?>
			<li id="<?php echo $_code ?>_store_in_vault_div" style="text-align:left;<?php echo ( $_loggedIn ) ? '' : 'display:none;' ?>" class="hide_if_token_selected">
				<input type="checkbox" title="<?php echo $this->__( 'Save this card for future use' ) ?>" class="input-checkbox" id="<?php echo $_code ?>_store_in_vault" name="payment[store_in_vault]" value="1" />
				<label for="<?php echo $_code ?>_store_in_vault" class="required" style="float:none;"><?php echo $this->__( 'Save this card for future use' ) ?></label>
			</li>
		<?php endif; ?>
	</div>
</ul>

<script type="text/javascript">
	//<![CDATA[

	var loggedIn = <?php echo ($_loggedIn) ? 'true' : 'false'; ?>;

	<?php if ($_useVault) { ?>
		var initToken = $('<?php echo $_code ?>_cc_token').getValue();
		if (initToken) {
			$$('.hide_if_token_selected').invoke('hide');
		}

		$('<?php echo $_code ?>_cc_token').observe('change',function(e){
			var token = $( this ).getValue();
			if (token) {
				$$('.hide_if_token_selected').invoke('hide');
			} else {
				$$('.hide_if_token_selected').invoke('show');
			}
		});
	<?php } ?>

	if ($$('#onestepcheckout-form').first() && !loggedIn ) {
		$('id_create_account').observe('change',function(){
			$('<?php echo $_code; ?>_store_in_vault_div').toggle();
		});
	} else if ($('co-payment-form')) {
		$$('.encrypted-field').each(function(element){
			element.remove();
		});
	}

	var braintree = Braintree.create( '<?php echo $_model->getConfigData( 'client_side_encryption_key' ); ?>' );

	//]]>
</script>